version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=sandip
      - DB_PASS=secret123
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=sandip
      - POSTGRES_PASSWORD=secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet: